# Generated by Django 3.2.6 on 2021-08-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='division',
            field=models.CharField(choices=[('D', 'Dhaka'), ('C', 'Chitagong'), ('R', 'Rajshahi'), ('K', 'Khulna'), ('B', 'Barishal'), ('S', 'Shylet')], default='D', max_length=20),
        ),
    ]
